# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_nbdev_Setup.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/02_nbdev_Setup.ipynb 35
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
